# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jiaogedan_test.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1366, 380)
        Form.setMinimumSize(QtCore.QSize(0, 380))
        Form.setMaximumSize(QtCore.QSize(2000, 380))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(16)
        Form.setFont(font)
        Form.setStyleSheet("")
        self.closeBtn = QtWidgets.QPushButton(Form)
        self.closeBtn.setGeometry(QtCore.QRect(0, 0, 16, 16))
        self.closeBtn.setText("")
        self.closeBtn.setFlat(True)
        self.closeBtn.setObjectName("closeBtn")
        self.frame00 = QtWidgets.QFrame(Form)
        self.frame00.setGeometry(QtCore.QRect(38, 5, 374, 218))
        self.frame00.setStyleSheet("#frame00{background:url(:/src/src/border.png);}")
        self.frame00.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame00.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame00.setObjectName("frame00")
        self.zlcBtn = QtWidgets.QPushButton(self.frame00)
        self.zlcBtn.setGeometry(QtCore.QRect(141, 50, 50, 20))
        self.zlcBtn.setStyleSheet("border-image:url(:/src/src/off.png)")
        self.zlcBtn.setObjectName("zlcBtn")
        self.fxdBtn = QtWidgets.QPushButton(self.frame00)
        self.fxdBtn.setGeometry(QtCore.QRect(134, 182, 58, 34))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.fxdBtn.setFont(font)
        self.fxdBtn.setStyleSheet("border-image:url(:/src/src/fxd.png);color:white")
        self.fxdBtn.setObjectName("fxdBtn")
        self.sellBtn = QtWidgets.QPushButton(self.frame00)
        self.sellBtn.setGeometry(QtCore.QRect(96, 75, 43, 20))
        self.sellBtn.setStyleSheet("border-image:url(:/src/src/off.png);color:rgb(5,192,5);")
        self.sellBtn.setObjectName("sellBtn")
        self.b5 = QtWidgets.QPushButton(self.frame00)
        self.b5.setGeometry(QtCore.QRect(247, 184, 56, 21))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(10)
        self.b5.setFont(font)
        self.b5.setStyleSheet("")
        self.b5.setFlat(True)
        self.b5.setObjectName("b5")
        self.kcBtn = QtWidgets.QPushButton(self.frame00)
        self.kcBtn.setGeometry(QtCore.QRect(50, 100, 43, 20))
        self.kcBtn.setStyleSheet("border-image:url(:/src/src/on.png);")
        self.kcBtn.setObjectName("kcBtn")
        self.s5 = QtWidgets.QPushButton(self.frame00)
        self.s5.setGeometry(QtCore.QRect(247, 23, 56, 21))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(10)
        self.s5.setFont(font)
        self.s5.setStyleSheet("")
        self.s5.setFlat(True)
        self.s5.setObjectName("s5")
        self.b1l = QtWidgets.QLabel(self.frame00)
        self.b1l.setGeometry(QtCore.QRect(312, 112, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(10)
        self.b1l.setFont(font)
        self.b1l.setObjectName("b1l")
        self.s5l = QtWidgets.QLabel(self.frame00)
        self.s5l.setGeometry(QtCore.QRect(312, 23, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(10)
        self.s5l.setFont(font)
        self.s5l.setObjectName("s5l")
        self.hyCombo = QtWidgets.QComboBox(self.frame00)
        self.hyCombo.setGeometry(QtCore.QRect(52, 25, 92, 21))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.hyCombo.setFont(font)
        self.hyCombo.setObjectName("hyCombo")
        self.hyCombo.addItem("")
        self.hyCombo.addItem("")
        self.hyCombo.addItem("")
        self.hyCombo.addItem("")
        self.hyCombo.addItem("")
        self.hyCombo.addItem("")
        self.hyCombo.addItem("")
        self.hyCombo.addItem("")
        self.hyCombo.addItem("")
        self.hyCombo.addItem("")
        self.s3 = QtWidgets.QPushButton(self.frame00)
        self.s3.setGeometry(QtCore.QRect(247, 60, 56, 21))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(10)
        self.s3.setFont(font)
        self.s3.setStyleSheet("")
        self.s3.setFlat(True)
        self.s3.setObjectName("s3")
        self.b4l = QtWidgets.QLabel(self.frame00)
        self.b4l.setGeometry(QtCore.QRect(312, 166, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(10)
        self.b4l.setFont(font)
        self.b4l.setObjectName("b4l")
        self.s2 = QtWidgets.QPushButton(self.frame00)
        self.s2.setGeometry(QtCore.QRect(247, 78, 56, 21))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(10)
        self.s2.setFont(font)
        self.s2.setStyleSheet("")
        self.s2.setFlat(True)
        self.s2.setObjectName("s2")
        self.yqBtn = QtWidgets.QPushButton(self.frame00)
        self.yqBtn.setGeometry(QtCore.QRect(50, 50, 43, 20))
        self.yqBtn.setStyleSheet("border-image:url(:/src/src/on.png)")
        self.yqBtn.setObjectName("yqBtn")
        self.b1 = QtWidgets.QPushButton(self.frame00)
        self.b1.setGeometry(QtCore.QRect(247, 112, 56, 21))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(10)
        self.b1.setFont(font)
        self.b1.setStyleSheet("")
        self.b1.setFlat(True)
        self.b1.setObjectName("b1")
        self.b3 = QtWidgets.QPushButton(self.frame00)
        self.b3.setGeometry(QtCore.QRect(247, 148, 56, 21))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(10)
        self.b3.setFont(font)
        self.b3.setStyleSheet("")
        self.b3.setFlat(True)
        self.b3.setObjectName("b3")
        self.ssSpin = QtWidgets.QSpinBox(self.frame00)
        self.ssSpin.setGeometry(QtCore.QRect(52, 125, 86, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.ssSpin.setFont(font)
        self.ssSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ssSpin.setObjectName("ssSpin")
        self.s2l = QtWidgets.QLabel(self.frame00)
        self.s2l.setGeometry(QtCore.QRect(312, 78, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(10)
        self.s2l.setFont(font)
        self.s2l.setObjectName("s2l")
        self.zdjSpin = QtWidgets.QDoubleSpinBox(self.frame00)
        self.zdjSpin.setGeometry(QtCore.QRect(52, 150, 86, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.zdjSpin.setFont(font)
        self.zdjSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.zdjSpin.setDecimals(0)
        self.zdjSpin.setMaximum(5000.0)
        self.zdjSpin.setSingleStep(1.0)
        self.zdjSpin.setObjectName("zdjSpin")
        self.b2l = QtWidgets.QLabel(self.frame00)
        self.b2l.setGeometry(QtCore.QRect(312, 130, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(10)
        self.b2l.setFont(font)
        self.b2l.setObjectName("b2l")
        self.zdjBtn = QtWidgets.QPushButton(self.frame00)
        self.zdjBtn.setGeometry(QtCore.QRect(7, 152, 41, 20))
        self.zdjBtn.setStyleSheet("QPushButton{border-image:url(:/src/src/zdj.png)} QPushButton:hover{color:red;}")
        self.zdjBtn.setObjectName("zdjBtn")
        self.s4l = QtWidgets.QLabel(self.frame00)
        self.s4l.setGeometry(QtCore.QRect(312, 41, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(10)
        self.s4l.setFont(font)
        self.s4l.setObjectName("s4l")
        self.s1 = QtWidgets.QPushButton(self.frame00)
        self.s1.setGeometry(QtCore.QRect(247, 94, 56, 21))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(10)
        self.s1.setFont(font)
        self.s1.setStyleSheet("")
        self.s1.setFlat(True)
        self.s1.setObjectName("s1")
        self.jsBtn = QtWidgets.QPushButton(self.frame00)
        self.jsBtn.setGeometry(QtCore.QRect(96, 50, 43, 20))
        self.jsBtn.setStyleSheet("border-image:url(:/src/src/off.png)")
        self.jsBtn.setObjectName("jsBtn")
        self.b2 = QtWidgets.QPushButton(self.frame00)
        self.b2.setGeometry(QtCore.QRect(247, 130, 56, 21))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(10)
        self.b2.setFont(font)
        self.b2.setStyleSheet("")
        self.b2.setFlat(True)
        self.b2.setObjectName("b2")
        self.buyBtn = QtWidgets.QPushButton(self.frame00)
        self.buyBtn.setGeometry(QtCore.QRect(50, 75, 43, 20))
        self.buyBtn.setStyleSheet("border-image:url(:/src/src/on.png);color:red;")
        self.buyBtn.setObjectName("buyBtn")
        self.s1l = QtWidgets.QLabel(self.frame00)
        self.s1l.setGeometry(QtCore.QRect(312, 94, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(10)
        self.s1l.setFont(font)
        self.s1l.setObjectName("s1l")
        self.b5l = QtWidgets.QLabel(self.frame00)
        self.b5l.setGeometry(QtCore.QRect(312, 184, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(10)
        self.b5l.setFont(font)
        self.b5l.setObjectName("b5l")
        self.b4 = QtWidgets.QPushButton(self.frame00)
        self.b4.setGeometry(QtCore.QRect(247, 166, 56, 21))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(10)
        self.b4.setFont(font)
        self.b4.setStyleSheet("")
        self.b4.setFlat(True)
        self.b4.setObjectName("b4")
        self.pcBtn = QtWidgets.QPushButton(self.frame00)
        self.pcBtn.setGeometry(QtCore.QRect(96, 100, 43, 20))
        self.pcBtn.setStyleSheet("border-image:url(:/src/src/off.png);")
        self.pcBtn.setObjectName("pcBtn")
        self.s4 = QtWidgets.QPushButton(self.frame00)
        self.s4.setGeometry(QtCore.QRect(247, 41, 56, 21))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(10)
        self.s4.setFont(font)
        self.s4.setStyleSheet("")
        self.s4.setFlat(True)
        self.s4.setObjectName("s4")
        self.pushButton = QtWidgets.QPushButton(self.frame00)
        self.pushButton.setGeometry(QtCore.QRect(77, 175, 47, 34))
        self.pushButton.setObjectName("pushButton")
        self.kdcBtn = QtWidgets.QPushButton(self.frame00)
        self.kdcBtn.setGeometry(QtCore.QRect(7, 175, 71, 34))
        self.kdcBtn.setObjectName("kdcBtn")
        self.b3l = QtWidgets.QLabel(self.frame00)
        self.b3l.setGeometry(QtCore.QRect(312, 148, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(10)
        self.b3l.setFont(font)
        self.b3l.setObjectName("b3l")
        self.s3l = QtWidgets.QLabel(self.frame00)
        self.s3l.setGeometry(QtCore.QRect(312, 60, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setPointSize(10)
        self.s3l.setFont(font)
        self.s3l.setObjectName("s3l")
        self.czBtn = QtWidgets.QPushButton(self.frame00)
        self.czBtn.setGeometry(QtCore.QRect(322, 2, 48, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.czBtn.setFont(font)
        self.czBtn.setStyleSheet("")
        self.czBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/src/src/cz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.czBtn.setIcon(icon)
        self.czBtn.setIconSize(QtCore.QSize(48, 16))
        self.czBtn.setFlat(True)
        self.czBtn.setObjectName("czBtn")
        self.dkLbl = QtWidgets.QLabel(self.frame00)
        self.dkLbl.setGeometry(QtCore.QRect(150, 28, 85, 17))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        self.dkLbl.setFont(font)
        self.dkLbl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dkLbl.setObjectName("dkLbl")
        self.ssLbl = QtWidgets.QLabel(self.frame00)
        self.ssLbl.setGeometry(QtCore.QRect(147, 127, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        self.ssLbl.setFont(font)
        self.ssLbl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ssLbl.setObjectName("ssLbl")
        self.zddLbl = QtWidgets.QLabel(self.frame00)
        self.zddLbl.setGeometry(QtCore.QRect(147, 145, 65, 17))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        self.zddLbl.setFont(font)
        self.zddLbl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.zddLbl.setObjectName("zddLbl")
        self.zdxLbl = QtWidgets.QLabel(self.frame00)
        self.zdxLbl.setGeometry(QtCore.QRect(147, 160, 64, 17))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        self.zdxLbl.setFont(font)
        self.zdxLbl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.zdxLbl.setObjectName("zdxLbl")
        self.label_2 = QtWidgets.QLabel(self.frame00)
        self.label_2.setGeometry(QtCore.QRect(24, 30, 30, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame00)
        self.label_3.setGeometry(QtCore.QRect(24, 56, 30, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame00)
        self.label_4.setGeometry(QtCore.QRect(24, 82, 30, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame00)
        self.label_5.setGeometry(QtCore.QRect(24, 104, 30, 12))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame00)
        self.label_6.setGeometry(QtCore.QRect(22, 130, 30, 12))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame00)
        self.label_7.setGeometry(QtCore.QRect(4, 2, 58, 18))
        self.label_7.setStyleSheet("border-image:url(:/src/src/xd.png)")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(self.frame00)
        self.label.setGeometry(QtCore.QRect(298, 25, 10, 180))
        self.label.setStyleSheet("border-image:url(:/src/src/xiegan.png)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.ssEdit = QtWidgets.QLineEdit(self.frame00)
        self.ssEdit.setGeometry(QtCore.QRect(164, 128, 74, 16))
        self.ssEdit.setObjectName("ssEdit")
        self.zddEdit = QtWidgets.QLineEdit(self.frame00)
        self.zddEdit.setGeometry(QtCore.QRect(164, 146, 74, 16))
        self.zddEdit.setObjectName("zddEdit")
        self.zdxEdit = QtWidgets.QLineEdit(self.frame00)
        self.zdxEdit.setGeometry(QtCore.QRect(164, 163, 75, 16))
        self.zdxEdit.setObjectName("zdxEdit")
        self.zlcBtn.raise_()
        self.fxdBtn.raise_()
        self.sellBtn.raise_()
        self.b5.raise_()
        self.s5.raise_()
        self.b1l.raise_()
        self.s5l.raise_()
        self.hyCombo.raise_()
        self.s3.raise_()
        self.b4l.raise_()
        self.s2.raise_()
        self.yqBtn.raise_()
        self.b1.raise_()
        self.b3.raise_()
        self.ssSpin.raise_()
        self.s2l.raise_()
        self.zdjSpin.raise_()
        self.b2l.raise_()
        self.zdjBtn.raise_()
        self.s4l.raise_()
        self.s1.raise_()
        self.jsBtn.raise_()
        self.b2.raise_()
        self.buyBtn.raise_()
        self.s1l.raise_()
        self.b5l.raise_()
        self.b4.raise_()
        self.pcBtn.raise_()
        self.s4.raise_()
        self.pushButton.raise_()
        self.kdcBtn.raise_()
        self.b3l.raise_()
        self.s3l.raise_()
        self.kcBtn.raise_()
        self.czBtn.raise_()
        self.dkLbl.raise_()
        self.ssLbl.raise_()
        self.zddLbl.raise_()
        self.zdxLbl.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label.raise_()
        self.ssEdit.raise_()
        self.zddEdit.raise_()
        self.zdxEdit.raise_()
        self.frame01 = QtWidgets.QFrame(Form)
        self.frame01.setGeometry(QtCore.QRect(415, 5, 945, 218))
        self.frame01.setStyleSheet("")
        self.frame01.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame01.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame01.setObjectName("frame01")
        self.sStack = QtWidgets.QStackedWidget(self.frame01)
        self.sStack.setGeometry(QtCore.QRect(3, 22, 939, 194))
        self.sStack.setStyleSheet("#frame01{background:url(:/src/src/border.png);}")
        self.sStack.setObjectName("sStack")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.bdTbl = QtWidgets.QTableWidget(self.page)
        self.bdTbl.setGeometry(QtCore.QRect(0, 0, 770, 194))
        self.bdTbl.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.bdTbl.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bdTbl.setFrameShadow(QtWidgets.QFrame.Plain)
        self.bdTbl.setColumnCount(11)
        self.bdTbl.setObjectName("bdTbl")
        self.bdTbl.setRowCount(0)
        self.bdTbl.horizontalHeader().setDefaultSectionSize(70)
        self.cdBtn = QtWidgets.QPushButton(self.page)
        self.cdBtn.setGeometry(QtCore.QRect(900, -1, 40, 66))
        self.cdBtn.setObjectName("cdBtn")
        self.qcBtn = QtWidgets.QPushButton(self.page)
        self.qcBtn.setGeometry(QtCore.QRect(900, 64, 40, 66))
        self.qcBtn.setObjectName("qcBtn")
        self.gdBtn = QtWidgets.QPushButton(self.page)
        self.gdBtn.setGeometry(QtCore.QRect(900, 129, 40, 66))
        self.gdBtn.setObjectName("gdBtn")
        self.sStack.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.ymdTbl = QtWidgets.QTableWidget(self.page_2)
        self.ymdTbl.setGeometry(QtCore.QRect(0, 0, 760, 161))
        self.ymdTbl.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ymdTbl.setColumnCount(8)
        self.ymdTbl.setObjectName("ymdTbl")
        self.ymdTbl.setRowCount(0)
        self.ymdTbl.horizontalHeader().setDefaultSectionSize(95)
        self.scBtn = QtWidgets.QPushButton(self.page_2)
        self.scBtn.setGeometry(QtCore.QRect(15, 165, 75, 23))
        self.scBtn.setObjectName("scBtn")
        self.ljBtn = QtWidgets.QPushButton(self.page_2)
        self.ljBtn.setGeometry(QtCore.QRect(100, 165, 75, 23))
        self.ljBtn.setObjectName("ljBtn")
        self.qkBtn = QtWidgets.QPushButton(self.page_2)
        self.qkBtn.setGeometry(QtCore.QRect(185, 165, 75, 23))
        self.qkBtn.setObjectName("qkBtn")
        self.sStack.addWidget(self.page_2)
        self.sLbl = QtWidgets.QLabel(self.frame01)
        self.sLbl.setGeometry(QtCore.QRect(4, 2, 152, 18))
        self.sLbl.setText("")
        self.sLbl.setPixmap(QtGui.QPixmap(":/src/src/bd.png"))
        self.sLbl.setScaledContents(True)
        self.sLbl.setObjectName("sLbl")
        self.bdTab = QtWidgets.QPushButton(self.frame01)
        self.bdTab.setGeometry(QtCore.QRect(8, -1, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.bdTab.setFont(font)
        self.bdTab.setFlat(True)
        self.bdTab.setObjectName("bdTab")
        self.ymdTab = QtWidgets.QPushButton(self.frame01)
        self.ymdTab.setGeometry(QtCore.QRect(84, -1, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.ymdTab.setFont(font)
        self.ymdTab.setFlat(True)
        self.ymdTab.setObjectName("ymdTab")
        self.frame10 = QtWidgets.QFrame(Form)
        self.frame10.setGeometry(QtCore.QRect(38, 226, 374, 151))
        self.frame10.setStyleSheet("#frame10{background:url(:/src/src/border.png);}")
        self.frame10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame10.setObjectName("frame10")
        self.tStack = QtWidgets.QStackedWidget(self.frame10)
        self.tStack.setGeometry(QtCore.QRect(2, 22, 370, 128))
        self.tStack.setObjectName("tStack")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.pcBtn2 = QtWidgets.QPushButton(self.page_3)
        self.pcBtn2.setGeometry(QtCore.QRect(330, -1, 41, 64))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        self.pcBtn2.setFont(font)
        self.pcBtn2.setObjectName("pcBtn2")
        self.fsBtn = QtWidgets.QPushButton(self.page_3)
        self.fsBtn.setGeometry(QtCore.QRect(330, 63, 41, 64))
        self.fsBtn.setObjectName("fsBtn")
        self.ccTbl = QtWidgets.QTableWidget(self.page_3)
        self.ccTbl.setGeometry(QtCore.QRect(-1, 0, 330, 127))
        self.ccTbl.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ccTbl.setColumnCount(10)
        self.ccTbl.setObjectName("ccTbl")
        self.ccTbl.setRowCount(0)
        self.ccTbl.horizontalHeader().setDefaultSectionSize(70)
        self.tStack.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.thBtn = QtWidgets.QPushButton(self.page_4)
        self.thBtn.setGeometry(QtCore.QRect(0, 105, 74, 23))
        self.thBtn.setObjectName("thBtn")
        self.kcTbl = QtWidgets.QTableWidget(self.page_4)
        self.kcTbl.setGeometry(QtCore.QRect(-2, 0, 280, 105))
        self.kcTbl.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.kcTbl.setColumnCount(4)
        self.kcTbl.setObjectName("kcTbl")
        self.kcTbl.setRowCount(0)
        self.kcTbl.horizontalHeader().setDefaultSectionSize(70)
        self.tStack.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.crjBtn = QtWidgets.QPushButton(self.page_5)
        self.crjBtn.setGeometry(QtCore.QRect(0, 105, 74, 23))
        self.crjBtn.setObjectName("crjBtn")
        self.zjTbl = QtWidgets.QTableWidget(self.page_5)
        self.zjTbl.setGeometry(QtCore.QRect(-2, 0, 360, 105))
        self.zjTbl.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.zjTbl.setColumnCount(4)
        self.zjTbl.setObjectName("zjTbl")
        self.zjTbl.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.zjTbl.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.zjTbl.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.zjTbl.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.zjTbl.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.zjTbl.setItem(0, 3, item)
        self.zjTbl.horizontalHeader().setDefaultSectionSize(90)
        self.zjTbl.verticalHeader().setVisible(False)
        self.tStack.addWidget(self.page_5)
        self.tLbl = QtWidgets.QLabel(self.frame10)
        self.tLbl.setGeometry(QtCore.QRect(0, 0, 185, 20))
        self.tLbl.setText("")
        self.tLbl.setPixmap(QtGui.QPixmap(":/src/src/cc.png"))
        self.tLbl.setScaledContents(True)
        self.tLbl.setObjectName("tLbl")
        self.zjTab = QtWidgets.QPushButton(self.frame10)
        self.zjTab.setGeometry(QtCore.QRect(122, -1, 55, 23))
        self.zjTab.setFlat(True)
        self.zjTab.setObjectName("zjTab")
        self.ccTab = QtWidgets.QPushButton(self.frame10)
        self.ccTab.setGeometry(QtCore.QRect(6, -1, 55, 23))
        self.ccTab.setFlat(True)
        self.ccTab.setObjectName("ccTab")
        self.kcTab = QtWidgets.QPushButton(self.frame10)
        self.kcTab.setGeometry(QtCore.QRect(64, -1, 55, 23))
        self.kcTab.setFlat(True)
        self.kcTab.setObjectName("kcTab")
        self.frame11 = QtWidgets.QFrame(Form)
        self.frame11.setGeometry(QtCore.QRect(415, 226, 945, 151))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.frame11.setFont(font)
        self.frame11.setStyleSheet("#frame11{background:url(:/src/src/border.png);border: 1px solid rgb(160,160,160); }")
        self.frame11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame11.setObjectName("frame11")
        self.cjTbl = QtWidgets.QTableWidget(self.frame11)
        self.cjTbl.setGeometry(QtCore.QRect(2, 23, 595, 121))
        self.cjTbl.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.cjTbl.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cjTbl.setColumnCount(7)
        self.cjTbl.setObjectName("cjTbl")
        self.cjTbl.setRowCount(0)
        self.cjTbl.horizontalHeader().setDefaultSectionSize(76)
        self.dragLbl1 = QtWidgets.QLabel(Form)
        self.dragLbl1.setGeometry(QtCore.QRect(412, 5, 3, 218))
        self.dragLbl1.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.dragLbl1.setStyleSheet("")
        self.dragLbl1.setText("")
        self.dragLbl1.setObjectName("dragLbl1")
        self.windowDragLbl = QtWidgets.QLabel(Form)
        self.windowDragLbl.setGeometry(QtCore.QRect(0, 72, 22, 306))
        self.windowDragLbl.setCursor(QtGui.QCursor(QtCore.Qt.SizeAllCursor))
        self.windowDragLbl.setText("")
        self.windowDragLbl.setObjectName("windowDragLbl")
        self.fLbl = QtWidgets.QLabel(Form)
        self.fLbl.setGeometry(QtCore.QRect(418, 226, 85, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.fLbl.setFont(font)
        self.fLbl.setStyleSheet("border-image:url(:/src/src/cjls.png)")
        self.fLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.fLbl.setObjectName("fLbl")
        self.dragLbl2 = QtWidgets.QLabel(Form)
        self.dragLbl2.setGeometry(QtCore.QRect(412, 226, 3, 151))
        self.dragLbl2.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.dragLbl2.setStyleSheet("")
        self.dragLbl2.setText("")
        self.dragLbl2.setObjectName("dragLbl2")
        self.sysBtn = QtWidgets.QPushButton(Form)
        self.sysBtn.setGeometry(QtCore.QRect(19, 6, 19, 48))
        self.sysBtn.setStyleSheet("")
        self.sysBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/src/src/sys.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sysBtn.setIcon(icon1)
        self.sysBtn.setIconSize(QtCore.QSize(19, 48))
        self.sysBtn.setFlat(True)
        self.sysBtn.setObjectName("sysBtn")

        self.retranslateUi(Form)
        self.sStack.setCurrentIndex(0)
        self.tStack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.zlcBtn.setText(_translate("Form", "中立仓"))
        self.fxdBtn.setText(_translate("Form", "0%"))
        self.sellBtn.setText(_translate("Form", "卖"))
        self.b5.setText(_translate("Form", "1524"))
        self.kcBtn.setText(_translate("Form", "开仓"))
        self.s5.setText(_translate("Form", "1524"))
        self.b1l.setText(_translate("Form", "1234"))
        self.s5l.setText(_translate("Form", "1234"))
        self.hyCombo.setItemText(0, _translate("Form", "Ag(T+D)"))
        self.hyCombo.setItemText(1, _translate("Form", "Au(T+D)"))
        self.hyCombo.setItemText(2, _translate("Form", "mAu(T+D)"))
        self.hyCombo.setItemText(3, _translate("Form", "Au99.99"))
        self.hyCombo.setItemText(4, _translate("Form", "Au100g"))
        self.hyCombo.setItemText(5, _translate("Form", "Au99.95"))
        self.hyCombo.setItemText(6, _translate("Form", "Pt99.95"))
        self.hyCombo.setItemText(7, _translate("Form", "Au(T+N1)"))
        self.hyCombo.setItemText(8, _translate("Form", "Au(T+N2)"))
        self.hyCombo.setItemText(9, _translate("Form", "Au99.5"))
        self.s3.setText(_translate("Form", "1524"))
        self.b4l.setText(_translate("Form", "1234"))
        self.s2.setText(_translate("Form", "1524"))
        self.yqBtn.setText(_translate("Form", "延期"))
        self.b1.setText(_translate("Form", "1524"))
        self.b3.setText(_translate("Form", "1524"))
        self.s2l.setText(_translate("Form", "1234"))
        self.b2l.setText(_translate("Form", "1234"))
        self.zdjBtn.setText(_translate("Form", "指定价"))
        self.s4l.setText(_translate("Form", "1234"))
        self.s1.setText(_translate("Form", "1524"))
        self.jsBtn.setText(_translate("Form", "交收"))
        self.b2.setText(_translate("Form", "1524"))
        self.buyBtn.setText(_translate("Form", "买"))
        self.s1l.setText(_translate("Form", "1234"))
        self.b5l.setText(_translate("Form", "1234"))
        self.b4.setText(_translate("Form", "1524"))
        self.pcBtn.setText(_translate("Form", "平仓"))
        self.s4.setText(_translate("Form", "1524"))
        self.pushButton.setText(_translate("Form", "预埋单"))
        self.kdcBtn.setText(_translate("Form", "开多仓"))
        self.b3l.setText(_translate("Form", "1234"))
        self.s3l.setText(_translate("Form", "1234"))
        self.dkLbl.setText(_translate("Form", "多:0  空:0"))
        self.ssLbl.setText(_translate("Form", "<= 0"))
        self.zddLbl.setText(_translate("Form", "<= 2290.00"))
        self.zdxLbl.setText(_translate("Form", ">= 1257.68"))
        self.label_2.setText(_translate("Form", "合约"))
        self.label_3.setText(_translate("Form", "方式"))
        self.label_4.setText(_translate("Form", "买卖"))
        self.label_5.setText(_translate("Form", "开平"))
        self.label_6.setText(_translate("Form", "手数"))
        self.label_7.setText(_translate("Form", "下单"))
        self.cdBtn.setText(_translate("Form", "撤单"))
        self.qcBtn.setText(_translate("Form", "全撤"))
        self.gdBtn.setText(_translate("Form", "改单"))
        self.scBtn.setText(_translate("Form", "删除"))
        self.ljBtn.setText(_translate("Form", "立即发送"))
        self.qkBtn.setText(_translate("Form", "清空已发送"))
        self.bdTab.setText(_translate("Form", "报单流水"))
        self.ymdTab.setText(_translate("Form", "预埋单"))
        self.pcBtn2.setText(_translate("Form", "平仓"))
        self.fsBtn.setText(_translate("Form", "反手"))
        self.thBtn.setText(_translate("Form", "提货"))
        self.crjBtn.setText(_translate("Form", "出入金"))
        item = self.zjTbl.verticalHeaderItem(0)
        item.setText(_translate("Form", "新建行"))
        __sortingEnabled = self.zjTbl.isSortingEnabled()
        self.zjTbl.setSortingEnabled(False)
        item = self.zjTbl.item(0, 0)
        item.setText(_translate("Form", "0"))
        item = self.zjTbl.item(0, 1)
        item.setText(_translate("Form", "0"))
        item = self.zjTbl.item(0, 2)
        item.setText(_translate("Form", "0"))
        item = self.zjTbl.item(0, 3)
        item.setText(_translate("Form", "0"))
        self.zjTbl.setSortingEnabled(__sortingEnabled)
        self.zjTab.setText(_translate("Form", "资金"))
        self.ccTab.setText(_translate("Form", "持仓"))
        self.kcTab.setText(_translate("Form", "库存"))
        self.fLbl.setText(_translate("Form", "成交流水"))

import jgd_rc
