# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1260, 620)
        Form.setMinimumSize(QtCore.QSize(1260, 620))
        Form.setMaximumSize(QtCore.QSize(1260, 620))
        self.tabWidget_4 = QtWidgets.QTabWidget(Form)
        self.tabWidget_4.setGeometry(QtCore.QRect(560, 360, 691, 251))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.cjTbl = QtWidgets.QTableWidget(self.tab_4)
        self.cjTbl.setGeometry(QtCore.QRect(10, 10, 661, 211))
        self.cjTbl.setObjectName("cjTbl")
        self.cjTbl.setColumnCount(0)
        self.cjTbl.setRowCount(0)
        self.tabWidget_4.addTab(self.tab_4, "")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 541, 341))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(40, 10, 41, 31))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(70, 10, 111, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 41, 31))
        self.label_2.setObjectName("label_2")
        self.yqBtn = QtWidgets.QPushButton(self.tab)
        self.yqBtn.setGeometry(QtCore.QRect(70, 50, 51, 31))
        self.yqBtn.setObjectName("yqBtn")
        self.jsBtn = QtWidgets.QPushButton(self.tab)
        self.jsBtn.setGeometry(QtCore.QRect(130, 50, 51, 31))
        self.jsBtn.setObjectName("jsBtn")
        self.zlcBtn = QtWidgets.QPushButton(self.tab)
        self.zlcBtn.setGeometry(QtCore.QRect(190, 50, 51, 31))
        self.zlcBtn.setObjectName("zlcBtn")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(40, 90, 51, 31))
        self.label_3.setObjectName("label_3")
        self.buyBtn = QtWidgets.QPushButton(self.tab)
        self.buyBtn.setGeometry(QtCore.QRect(70, 90, 51, 31))
        self.buyBtn.setObjectName("buyBtn")
        self.sellBtn = QtWidgets.QPushButton(self.tab)
        self.sellBtn.setGeometry(QtCore.QRect(130, 90, 51, 31))
        self.sellBtn.setObjectName("sellBtn")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(40, 130, 51, 31))
        self.label_4.setObjectName("label_4")
        self.kcBtn = QtWidgets.QPushButton(self.tab)
        self.kcBtn.setGeometry(QtCore.QRect(70, 130, 51, 31))
        self.kcBtn.setObjectName("kcBtn")
        self.pcBtn = QtWidgets.QPushButton(self.tab)
        self.pcBtn.setGeometry(QtCore.QRect(130, 130, 51, 31))
        self.pcBtn.setObjectName("pcBtn")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(40, 170, 31, 31))
        self.label_5.setObjectName("label_5")
        self.ssSpin = QtWidgets.QSpinBox(self.tab)
        self.ssSpin.setGeometry(QtCore.QRect(70, 170, 111, 31))
        self.ssSpin.setObjectName("ssSpin")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(10, 210, 51, 31))
        self.pushButton.setObjectName("pushButton")
        self.zdSpin = QtWidgets.QSpinBox(self.tab)
        self.zdSpin.setGeometry(QtCore.QRect(70, 210, 111, 31))
        self.zdSpin.setObjectName("zdSpin")
        self.kdcBtn = QtWidgets.QPushButton(self.tab)
        self.kdcBtn.setGeometry(QtCore.QRect(10, 260, 71, 41))
        self.kdcBtn.setObjectName("kdcBtn")
        self.ymdBtn = QtWidgets.QPushButton(self.tab)
        self.ymdBtn.setGeometry(QtCore.QRect(90, 260, 71, 41))
        self.ymdBtn.setObjectName("ymdBtn")
        self.ymdBtn_2 = QtWidgets.QPushButton(self.tab)
        self.ymdBtn_2.setGeometry(QtCore.QRect(170, 260, 101, 41))
        self.ymdBtn_2.setObjectName("ymdBtn_2")
        self.hyLbl = QtWidgets.QLabel(self.tab)
        self.hyLbl.setGeometry(QtCore.QRect(200, 12, 71, 31))
        self.hyLbl.setObjectName("hyLbl")
        self.ssLbl = QtWidgets.QLabel(self.tab)
        self.ssLbl.setGeometry(QtCore.QRect(190, 170, 71, 31))
        self.ssLbl.setObjectName("ssLbl")
        self.zdMaxLbl = QtWidgets.QLabel(self.tab)
        self.zdMaxLbl.setGeometry(QtCore.QRect(190, 190, 71, 31))
        self.zdMaxLbl.setObjectName("zdMaxLbl")
        self.zdMinLbl = QtWidgets.QLabel(self.tab)
        self.zdMinLbl.setGeometry(QtCore.QRect(190, 220, 71, 31))
        self.zdMinLbl.setObjectName("zdMinLbl")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(320, 10, 31, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(320, 40, 31, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(320, 70, 31, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(320, 100, 31, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(320, 130, 31, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(320, 160, 31, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(320, 190, 31, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(320, 220, 31, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(320, 250, 31, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(320, 280, 31, 21))
        self.label_15.setObjectName("label_15")
        self.s5 = QtWidgets.QPushButton(self.tab)
        self.s5.setGeometry(QtCore.QRect(350, 10, 75, 23))
        self.s5.setObjectName("s5")
        self.s4 = QtWidgets.QPushButton(self.tab)
        self.s4.setGeometry(QtCore.QRect(350, 40, 75, 23))
        self.s4.setObjectName("s4")
        self.s3 = QtWidgets.QPushButton(self.tab)
        self.s3.setGeometry(QtCore.QRect(350, 70, 75, 23))
        self.s3.setObjectName("s3")
        self.s2 = QtWidgets.QPushButton(self.tab)
        self.s2.setGeometry(QtCore.QRect(350, 100, 75, 23))
        self.s2.setObjectName("s2")
        self.s1 = QtWidgets.QPushButton(self.tab)
        self.s1.setGeometry(QtCore.QRect(350, 130, 75, 23))
        self.s1.setObjectName("s1")
        self.b1 = QtWidgets.QPushButton(self.tab)
        self.b1.setGeometry(QtCore.QRect(350, 160, 75, 23))
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(self.tab)
        self.b2.setGeometry(QtCore.QRect(350, 190, 75, 23))
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QPushButton(self.tab)
        self.b3.setGeometry(QtCore.QRect(350, 220, 75, 23))
        self.b3.setObjectName("b3")
        self.b4 = QtWidgets.QPushButton(self.tab)
        self.b4.setGeometry(QtCore.QRect(350, 250, 75, 23))
        self.b4.setObjectName("b4")
        self.b5 = QtWidgets.QPushButton(self.tab)
        self.b5.setGeometry(QtCore.QRect(350, 280, 75, 23))
        self.b5.setObjectName("b5")
        self.sl5 = QtWidgets.QLabel(self.tab)
        self.sl5.setGeometry(QtCore.QRect(450, 10, 71, 21))
        self.sl5.setObjectName("sl5")
        self.sl4 = QtWidgets.QLabel(self.tab)
        self.sl4.setGeometry(QtCore.QRect(450, 40, 71, 21))
        self.sl4.setObjectName("sl4")
        self.sl3 = QtWidgets.QLabel(self.tab)
        self.sl3.setGeometry(QtCore.QRect(450, 70, 71, 21))
        self.sl3.setObjectName("sl3")
        self.sl2 = QtWidgets.QLabel(self.tab)
        self.sl2.setGeometry(QtCore.QRect(450, 100, 71, 21))
        self.sl2.setObjectName("sl2")
        self.sl1 = QtWidgets.QLabel(self.tab)
        self.sl1.setGeometry(QtCore.QRect(450, 130, 71, 21))
        self.sl1.setObjectName("sl1")
        self.bl1 = QtWidgets.QLabel(self.tab)
        self.bl1.setGeometry(QtCore.QRect(450, 160, 71, 21))
        self.bl1.setObjectName("bl1")
        self.bl2 = QtWidgets.QLabel(self.tab)
        self.bl2.setGeometry(QtCore.QRect(450, 190, 71, 21))
        self.bl2.setObjectName("bl2")
        self.bl3 = QtWidgets.QLabel(self.tab)
        self.bl3.setGeometry(QtCore.QRect(450, 220, 71, 21))
        self.bl3.setObjectName("bl3")
        self.bl4 = QtWidgets.QLabel(self.tab)
        self.bl4.setGeometry(QtCore.QRect(450, 250, 71, 21))
        self.bl4.setObjectName("bl4")
        self.bl5 = QtWidgets.QLabel(self.tab)
        self.bl5.setGeometry(QtCore.QRect(450, 280, 71, 21))
        self.bl5.setObjectName("bl5")
        self.tabWidget.addTab(self.tab, "")
        self.tabWidget_3 = QtWidgets.QTabWidget(Form)
        self.tabWidget_3.setGeometry(QtCore.QRect(10, 360, 541, 251))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.ccTbl = QtWidgets.QTableWidget(self.tab_3)
        self.ccTbl.setGeometry(QtCore.QRect(10, 10, 511, 171))
        self.ccTbl.setObjectName("ccTbl")
        self.ccTbl.setColumnCount(0)
        self.ccTbl.setRowCount(0)
        self.pcBtn2 = QtWidgets.QPushButton(self.tab_3)
        self.pcBtn2.setGeometry(QtCore.QRect(10, 190, 75, 31))
        self.pcBtn2.setObjectName("pcBtn2")
        self.fsBtn = QtWidgets.QPushButton(self.tab_3)
        self.fsBtn.setGeometry(QtCore.QRect(100, 190, 75, 31))
        self.fsBtn.setObjectName("fsBtn")
        self.tabWidget_3.addTab(self.tab_3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.kcTbl = QtWidgets.QTableWidget(self.tab_6)
        self.kcTbl.setGeometry(QtCore.QRect(10, 10, 511, 171))
        self.kcTbl.setObjectName("kcTbl")
        self.kcTbl.setColumnCount(0)
        self.kcTbl.setRowCount(0)
        self.thBtn = QtWidgets.QPushButton(self.tab_6)
        self.thBtn.setGeometry(QtCore.QRect(10, 190, 75, 31))
        self.thBtn.setObjectName("thBtn")
        self.tabWidget_3.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget.setGeometry(QtCore.QRect(10, 11, 511, 171))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.crjBtn = QtWidgets.QPushButton(self.tab_7)
        self.crjBtn.setGeometry(QtCore.QRect(10, 190, 75, 31))
        self.crjBtn.setObjectName("crjBtn")
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tabWidget_2 = QtWidgets.QTabWidget(Form)
        self.tabWidget_2.setGeometry(QtCore.QRect(560, 10, 691, 341))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.bdTbl = QtWidgets.QTableWidget(self.tab_5)
        self.bdTbl.setGeometry(QtCore.QRect(10, 10, 611, 301))
        self.bdTbl.setObjectName("bdTbl")
        self.bdTbl.setColumnCount(0)
        self.bdTbl.setRowCount(0)
        self.cdBtn = QtWidgets.QPushButton(self.tab_5)
        self.cdBtn.setGeometry(QtCore.QRect(630, 10, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cdBtn.setFont(font)
        self.cdBtn.setObjectName("cdBtn")
        self.qcBtn = QtWidgets.QPushButton(self.tab_5)
        self.qcBtn.setGeometry(QtCore.QRect(630, 60, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.qcBtn.setFont(font)
        self.qcBtn.setObjectName("qcBtn")
        self.gdBtn = QtWidgets.QPushButton(self.tab_5)
        self.gdBtn.setGeometry(QtCore.QRect(630, 110, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.gdBtn.setFont(font)
        self.gdBtn.setObjectName("gdBtn")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.ymdTbl = QtWidgets.QTableWidget(self.tab_2)
        self.ymdTbl.setGeometry(QtCore.QRect(10, 10, 661, 261))
        self.ymdTbl.setObjectName("ymdTbl")
        self.ymdTbl.setColumnCount(0)
        self.ymdTbl.setRowCount(0)
        self.scBtn = QtWidgets.QPushButton(self.tab_2)
        self.scBtn.setGeometry(QtCore.QRect(10, 280, 75, 31))
        self.scBtn.setObjectName("scBtn")
        self.ljfsBtn = QtWidgets.QPushButton(self.tab_2)
        self.ljfsBtn.setGeometry(QtCore.QRect(100, 280, 75, 31))
        self.ljfsBtn.setObjectName("ljfsBtn")
        self.qkyfsBtn = QtWidgets.QPushButton(self.tab_2)
        self.qkyfsBtn.setGeometry(QtCore.QRect(190, 280, 75, 31))
        self.qkyfsBtn.setObjectName("qkyfsBtn")
        self.tabWidget_2.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "股票交割单生成器"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_4), _translate("Form", "成交流水"))
        self.label.setText(_translate("Form", "合约"))
        self.comboBox.setItemText(0, _translate("Form", "Ag (T + D)"))
        self.comboBox.setItemText(1, _translate("Form", "Au (T + D)"))
        self.comboBox.setItemText(2, _translate("Form", "mAu (T + D)"))
        self.comboBox.setItemText(3, _translate("Form", "Au 99.99"))
        self.comboBox.setItemText(4, _translate("Form", "Au 100g"))
        self.comboBox.setItemText(5, _translate("Form", "Au 99.95"))
        self.comboBox.setItemText(6, _translate("Form", "Pt 99.95"))
        self.comboBox.setItemText(7, _translate("Form", "Au (T + N1)"))
        self.comboBox.setItemText(8, _translate("Form", "Au (T + N2)"))
        self.comboBox.setItemText(9, _translate("Form", "Au 99.5"))
        self.label_2.setText(_translate("Form", "方式"))
        self.yqBtn.setText(_translate("Form", "延期"))
        self.jsBtn.setText(_translate("Form", "交收"))
        self.zlcBtn.setText(_translate("Form", "中立仓"))
        self.label_3.setText(_translate("Form", "买卖"))
        self.buyBtn.setText(_translate("Form", "买"))
        self.sellBtn.setText(_translate("Form", "卖"))
        self.label_4.setText(_translate("Form", "开平"))
        self.kcBtn.setText(_translate("Form", "开仓"))
        self.pcBtn.setText(_translate("Form", "平仓"))
        self.label_5.setText(_translate("Form", "手数"))
        self.pushButton.setText(_translate("Form", "指定价"))
        self.kdcBtn.setText(_translate("Form", "开多仓"))
        self.ymdBtn.setText(_translate("Form", "预埋单"))
        self.ymdBtn_2.setText(_translate("Form", "风险度 0%"))
        self.hyLbl.setText(_translate("Form", "多:0  空:0"))
        self.ssLbl.setText(_translate("Form", "<= 0"))
        self.zdMaxLbl.setText(_translate("Form", "<= 4420.00"))
        self.zdMinLbl.setText(_translate("Form", ">= 3765.00"))
        self.label_6.setText(_translate("Form", "卖5"))
        self.label_7.setText(_translate("Form", "卖4"))
        self.label_8.setText(_translate("Form", "卖3"))
        self.label_9.setText(_translate("Form", "卖2"))
        self.label_10.setText(_translate("Form", "卖1"))
        self.label_11.setText(_translate("Form", "买1"))
        self.label_12.setText(_translate("Form", "买2"))
        self.label_13.setText(_translate("Form", "买3"))
        self.label_14.setText(_translate("Form", "买4"))
        self.label_15.setText(_translate("Form", "买5"))
        self.s5.setText(_translate("Form", "0000"))
        self.s4.setText(_translate("Form", "0000"))
        self.s3.setText(_translate("Form", "0000"))
        self.s2.setText(_translate("Form", "0000"))
        self.s1.setText(_translate("Form", "0000"))
        self.b1.setText(_translate("Form", "0000"))
        self.b2.setText(_translate("Form", "0000"))
        self.b3.setText(_translate("Form", "0000"))
        self.b4.setText(_translate("Form", "0000"))
        self.b5.setText(_translate("Form", "0000"))
        self.sl5.setText(_translate("Form", "/  0000"))
        self.sl4.setText(_translate("Form", "/  0000"))
        self.sl3.setText(_translate("Form", "/  0000"))
        self.sl2.setText(_translate("Form", "/  0000"))
        self.sl1.setText(_translate("Form", "/  0000"))
        self.bl1.setText(_translate("Form", "/  0000"))
        self.bl2.setText(_translate("Form", "/  0000"))
        self.bl3.setText(_translate("Form", "/  0000"))
        self.bl4.setText(_translate("Form", "/  0000"))
        self.bl5.setText(_translate("Form", "/  0000"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "下单"))
        self.pcBtn2.setText(_translate("Form", "平仓"))
        self.fsBtn.setText(_translate("Form", "反手"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_3), _translate("Form", "持仓"))
        self.thBtn.setText(_translate("Form", "提货"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("Form", "库存"))
        self.crjBtn.setText(_translate("Form", "出入金"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("Form", "资金"))
        self.cdBtn.setText(_translate("Form", "撤单"))
        self.qcBtn.setText(_translate("Form", "全撤"))
        self.gdBtn.setText(_translate("Form", " 改单"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Form", "报单流水"))
        self.scBtn.setText(_translate("Form", "删除"))
        self.ljfsBtn.setText(_translate("Form", "立即发送"))
        self.qkyfsBtn.setText(_translate("Form", "清空已发送"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("Form", "预埋单"))

